### PR TITLE
Updated till latest update 2f8f1ec

### PR DESCRIPTION
**Pull request by bhumijgupta**
As promised in #30 , I have migrated all the updates in pep8 up until the latest commit https://github.com/python/peps/commit/2f8f1ec0ba92df5db85e9f78e7c2f422739ef1ec.
To my knowledge, the pep8.org is fully updated and in sync with the [pep8 document](https://github.com/python/peps/blob/master/pep-0008.txt).

Hope this helps.
Regards,
Bhumij Gupta

### CODE REVIEW

**Comment by bhumijgupta** [comment]
@kenneth-reitz please review!

**Comment by dbader** [comment]
@bhumijgupta Thanks! There's one merge conflict that needs to be resolved but then we're good to go :)

**Comment by bhumijgupta** [comment]
> @bhumijgupta Thanks! There's one merge conflict that needs to be resolved but then we're good to go :)

@dbader I resolved the merge conflict. The PR can be merged now!

**Comment by dbader** [comment]
Awesome, thanks @bhumijgupta

**Comment by bhumijgupta** [comment]
Happy to contribute!! 😄

**Pull request merged**
