### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by bushyn**
Ruff demo of a table of contents
(shows up on width >1070px )

### CODE REVIEW

**Comment by sergiocorreia** [comment]
Looks good but two questions:
1. Wouldn't it be better to have the TOC on the left side of the content, instead of moving the content to the right:

image
1. I would advise to remove h3 from the TOC. Otherwise, on medium screens (laptops, etc.) you end up with a weird scroll bar:

image

**Comment by kennethreitz** [comment]
this is fantastic!

I made some changes and pushed this to production. I'd like to make it so that it stays up at the top though, not following the rest of the document as you scroll. Can you do that please?

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
actually, this is nice, I see what's going on now. The problem I have is that there's a scrollbar that is always there on safari — i'd like to get rid of that unless it's being actively used.

**Comment by kennethreitz** [comment]
https://cl.ly/2l1Y0G3i0w47/Screen%20Shot%202016-11-20%20at%203.32.10%20PM.png

**Comment by kennethreitz** [comment]
i'm on a beta safari though, so maybe that's just something that's coming through the pipeline

**Comment by FichteFoll** [comment]
@sergiocorreia, I experimented a bit with css and always centering the actual content while attaching the navbar to the left. While it looks better in practive, imo, it requires a window width of 1400px to not clip out of bounds, which is >1280 and thus not exactly an option.

The css needed is roughly equivalent to this:

```css
@media(min-width: 1400px) {
  ...
}

.toc + .nine.columns {
  max-width: 750px;
  margin: 4em auto 0;
  float: none;
}

.toc {
  margin-left: -120px;
}
```

That could be entirely wrong because I was iterating a lot and don't exactly remmeber what I changed.

**Pull request merged**
